export const GET_INITIAL_VALUE = "GET_INITIAL_VALUE"
export const GET_INITIAL = "GET_INITIAL"

// Login event
export const CREATE_LOGIN_SUCCESS = "CREATE_LOGIN_SUCCESS"
export const CREATE_LOGIN_ERROR = "CREATE_LOGIN_ERROR"

// Registration event
export const CREATE_REGITRATION_SUCCESS = "CREATE_REGITRATION_SUCCESS"
export const CREATE_REGITRATION_ERROR = "CREATE_REGITRATION_ERROR"

// Otp code verification
export const OTP_VERIFICATION_SUCCESS = "OTP_VERIFICATION_SUCCESS"
export const OTP_VERIFICATION_ERROR = "OTP_VERIFICATION_ERROR"

// Resend Otp code verification
export const RESEND_OTP_VERIFICATION_SUCCESS = "RESEND_OTP_VERIFICATION_SUCCESS"
export const RESEND_OTP_VERIFICATION_ERROR = "RESEND_OTP_VERIFICATION_ERROR"

export const CREATE_PASSWORD_SUCCESS = "CREATE_PASSWORD_SUCCESS"
export const CREATE_PASSWORD_ERROR = "CREATE_PASSWORD_ERROR"

export const FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS"
export const FORGET_PASSWORD_ERROR = "FORGET_PASSWORD_ERROR"

export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS"
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR"

export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS"
export const VERIFY_OTP_ERROR = "VERIFY_OTP_ERROR"

// User-Profile
export const GET_USER_DETAILS = "GET_USER_DETAILS"
export const GET_USER_DETAILS_ERROR = "GET_USER_DETAILS_ERROR"

// User Update
export const UPADTE_USER_DETAILS = "UPADTE_USER_DETAILS"
export const UPADTE_USER_DETAILS_ERROR = "UPADTE_USER_DETAILS_ERROR"

// Drawer Data
export const GET_DRAWER_DATA = "GET_DRAWER_DATA"
export const GET_DRAWER_DATA_ERROR = "GET_DRAWER_DATA_ERROR"

// User Profile
export const UPLOAD_PROFILE_PIC = "UPLOAD_PROFILE_PIC"
export const UPLOAD_PROFILE_PIC_ERROR = "UPLOAD_PROFILE_PIC_ERROR"

//Country data
export const GET_COUNTRY = "GET_COUNTRY"
export const GET_COUNTRY_ERROR = "GET_COUNTRY_ERROR"


//State data
export const GET_STATE = "GET_STATE"
export const GET_STATE_ERROR = "GET_STATE_ERROR"

//City data
export const GET_CITY = "GET_CITY"
export const GET_CITY_ERROR = "GET_CITY_ERROR"

// Service Date
export const GET_NEXTSERVICE_DATE = "GET_NEXTSERVICE_DATE"
export const GET_NEXTSERVICE_DATE_ERROR = "GET_NEXTSERVICE_DATE_ERROR"

// Expiring Services
export const GET_EXP_SERVICES = "GET_EXP_SERVICES"
export const GET_EXP_SERVICES_ERROR = "GET_EXP_SERVICES_ERROR"

// Service details
export const GET_SERVICE_DETAILS_SUCCESS = "GET_SERVICE_DETAILS_SUCCESS"
export const GET_SERVICE_DETAILS_ERROR = "GET_SERVICE_DETAILS_ERROR"

// Report Fields
export const GET_REPORT_FIELDS = "GET_REPORT_FIELDS"
export const GET_REPORT_FIELDS_ERROR = "GET_REPORT_FIELDS_ERROR"

export const DOWNLOAD_REPORT_SUCCESS = "DOWNLOAD_REPORT_SUCCESS"
export const DOWNLOAD_REPORT_ERROR = "DOWNLOAD_REPORT_ERROR"

// Services List
export const GET_SERVICES_LIST = "GET_SERVICES_LIST"
export const GET_SERVICES_LIST_ERROR = "GET_SERVICES_LIST_ERROR"

// Create Services
export const SERVICE_CREATE = "SERVICE_CREATE"
export const SERVICE_CREATE_ERROR = "SERVICE_CREATE_ERROR"

// Renew Service
export const RENEW_SERVICE = "RENEW_SERVICE"
export const RENEW_SERVICE_ERROR = "RENEW_SERVICE_ERROR"

// Address
export const GET_ADDRESS_SUCCESS = "GET_ADDRESS_SUCCESS"
export const GET_ADDRESS_ERROR = "GET_ADDRESS_ERROR"




// Category FlatList
export const GET_CATEGORY_LIST = "GET_CATEGORY_LIST"
export const GET_CATEGORY_LIST_ERROR = "GET_CATEGORY_LIST_ERROR"

// Products List
export const GET_PRODUCTS_LIST = "GET_PRODUCTS_LIST"
export const GET_PRODUCTS_LIST_ERROR = "GET_PRODUCTS_LIST_ERROR"

//AddToCart
export const ADD_TO_CART = "ADD_TO_CART"
export const ADD_TO_CART_ERROR = "ADD_TO_CART_ERROR"

export const GET_ITEM_TOTAL = "GET_ITEM_TOTAL"
export const GET_ITEM_TOTAL_ERROR = "GET_ITEM_TOTAL_ERROR"

export const GET_CART_ITEM = "GET_CART_ITEM"
export const GET_CART_ITEM_ERROR = "GET_CART_ITEM_ERROR"

export const GET_TAX_SUCCESS = "GET_TAX_SUCCESS"
export const GET_TAX_ERROR = "GET_TAX_ERROR"


//Remove From Cart
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART"
export const REMOVE_ITEM_FROM_CART_ERROR = "REMOVE_ITEM_FROM_CART_ERROR"


// Checkout
export const CHECKOUT_CART = "CHECKOUT_CART"
export const CHECKOUT_CART_ERROR = "CHECKOUT_CART_ERROR"


// Reorder
export const REORDER_ITEMS = "REORDER_ITEMS"
export const REORDER_ITEMS_ERROR = "REORDER_ITEMS_ERROR"


// Invoices List
export const GET_INVOICES_LIST = "GET_INVOICES_LIST"
export const GET_INVOICES_LIST_ERROR = "GET_INVOICES_LIST_ERROR"

// Invoices Detail
export const GET_INVOICE_DETAILS = "GET_INVOICE_DETAILS"
export const GET_INVOICE_DETAILS_ERROR = "GET_INVOICE_DETAILS_ERROR"


// Transaction
export const CART_INVOICE_TRANSACTION = "CART_INVOICE_TRANSACTION"
export const CART_INVOICE_TRANSACTION_ERROR = "CART_INVOICE_TRANSACTION_ERROR"


// Latest Orders
export const GET_LATEST_ORDERS = "GET_LATEST_ORDERS"
export const GET_LATEST_ORDERS_ERROR = "GET_LATEST_ORDERS_ERROR"


// Tickets List
export const GET_TICKETS_LIST = "GET_TICKETS_LIST"
export const GET_TICKETS_LIST_ERROR = "GET_TICKETS_LIST_ERROR"

export const GET_ONGOING_TICKETS_LIST = "GET_ONGOING_TICKETS_LIST"
export const GET_ONGOING_TICKETS_LIST_ERROR = "GET_ONGOING_TICKETS_LIST_ERROR"



export const CREATE_NEW_TICKET = "CREATE_NEW_TICKET"
export const CREATE_NEW_TICKET_ERROR = "CREATE_NEW_TICKET_ERROR"


export const GET_TICKET_DETAILS = "GET_TICKET_DETAILS"
export const GET_TICKET_DETAILS_ERROR = "GET_TICKET_DETAILS_ERROR"


export const GET_SERVICES_UUID = "GET_SERVICES_UUID"
export const GET_SERVICES_UUID_ERROR = "GET_SERVICES_UUID_ERROR"


// Notes
export const CREATE_NEW_NOTES = "CREATE_NEW_NOTES"
export const CREATE_NEW_NOTES_ERROR = "CREATE_NEW_NOTES_ERROR"


// Notes Delete
export const DELETE_NOTE = "DELETE_NOTE"
export const DELETE_NOTE_ERROR = "DELETE_NOTE_ERROR"


// CashBook
export const GET_CASH_BOOK = "GET_CASH_BOOK"
export const GET_CASH_BOOK_ERROR = "GET_CASH_BOOK_ERROR"


// Report View
export const GET_REPORT_VIEW_SUCCESS = "GET_REPORT_VIEW_SUCCESS"
export const GET_REPORT_VIEW_ERROR = "GET_REPORT_VIEW_ERROR"

// Rate
export const RATING_TICKET_SUCCESS = "RATING_TICKET_SUCCESS"
export const RATING_TICKET_ERROR = "RATING_TICKET_ERROR"

// Service Cost
export const SERVICE_COST = "SERVICE_COST"
export const SERVICE_COST_ERROR = "SERVICE_COST_ERROR"

// in Cash
// Checkout ID
export const PAY_IN_CASH_SUCCESS = "PAY_IN_CASH_SUCCESS"
export const PAY_IN_CASH_ERROR = "PAY_IN_CASH_ERROR"


// Checkout ID
export const GET_CHECKOUT_ID_SUCCESS = "GET_CHECKOUT_ID_SUCCESS"
export const GET_CHECKOUT_ID_ERROR = "GET_CHECKOUT_ID_ERROR"

export const GET_INITIAL_SERVICES_LIST = "GET_INITIAL_SERVICES_LIST"

export const GET_INITIAL_TICKETS_LIST = "GET_INITIAL_TICKETS_LIST"

export const GET_INITIAL_PRODUCTS_LIST = "GET_INITIAL_PRODUCTS_LIST"

export const GET_INITIAL_CASH_BOOK = "GET_INITIAL_CASH_BOOK"

export const GET_INITIAL_INVOICES_LIST = "GET_INITIAL_INVOICES_LIST"

//Email
export const SEND_EMAIL_SUCCESS = "SEND_EMAIL_SUCCESS"

export const SEND_EMAIL_ERROR = "SEND_EMAIL_ERROR"
